# .github/workflows/firebase-hosting.yml
name: Deploy to Firebase Hosting on push

on: push

permissions:
  checks: write
  contents: read

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # pnpm 설치
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # 현재 사용 중인 pnpm 버전에 맞게 설정

      # 의존성 설치
      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install

      # Firebase 배포
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_POMODORO_RANK_TIMER }}
          projectId: pomodoro-rank-timer
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
